version: "3"
services:
  scraping-env:
    container_name: scraping-env

    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${http_proxy}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${https_proxy}
        - FTP_PROXY=${FTP_PROXY}
        - ftp_proxy=${ftp_proxy}

    environment:
      - BEARER_TOKEN=${BEARER_TOKEN}
      - API_TYPE=${API_TYPE}

    volumes:
      - ./:/workspace

    tty: true
